Get ProjectImportProvider builder in doGetBuilder instead of constructor
Fixes #1634

Fixes use of deprecated constructor dependency injection that is
incompatible with dynamic, injectable plugins in 2020.1.

```
com.intellij.diagnostic.PluginException: getComponentAdapterOfType is
used to get org.elixir_lang.mix.project._import.Builder(
  requestorClass=org.elixir_lang.mix.project._import.Provider,
  requestorConstructor=protected org.elixir_lang.mix.project._import.Provider(org.elixir_lang.mix.project._import.Builder)
).

Probably constructor should be marked as NonInjectable. [Plugin: org.elixir_lang]
```