Try splitting verifyPlugin due to OOM issues
https://github.com/KronicDeth/intellij-elixir/actions/runs/25866109080/job/76008523413?pr=3814#step:6:1388

Error: Exception in thread "OkHttp TaskRunner" Exception in thread
"OkHttp TaskRunner" java.lang.OutOfMemoryError: Java heap space
  java.lang.OutOfMemoryError: Java heap space
Error: Exception in thread "main" java.lang.RuntimeException: Worker
'org.elixir_lang:23.0.7-pre+20260514143824 against IU-253.30387.90'
finished with error