Use paths relative to `/bin` in cliArgs
I don't know why, but some dependencies won't compile if absolute paths are used for libs in the `-pa` parameters of the erlang cli. This ensures that the paths match those generated by the `elixir` cli tool.

Specific error seen with 1.15.7 & OTP 25 during `mix deps.compile`:
```
==> benchfella
Compiling 9 files (.ex)
error: module EEx is not loaded and could not be found
  lib/mix/tasks/bench_graph.ex:89: Mix.Tasks.Bench.Graph (module)
```