Update IDEAVim to 0.56
0.48 is incompatible with 2020.1 testing by causing

```
java.lang.IllegalStateException: @NotNull method com/maddyhome/idea/vim/VimPlugin.getInstance must not return null
```